1. Create a frequency table of ungrouped data

    10, 20, 30, 40, 10, 20, 100, 50, 60, 30, 20, 20, 10

    Observation           Frequency
    10              
    20
    30
    40
    50
    60
    100
    
    
2. Create a frequency table for grouped data


3. Create frequency table using inclusive method
4. Create frequency percentage table

5. Use exclusive method to create classes and calculate less than and more than cummulative Frequency table
6. Calculate Cummulative Percentage Freq. Table
7. Calculate mean for grouped data
8. Calculate mean for ungrouped/ descrete frequency distribution
9. Calculate weighted mean for data
10. Median for for ungrouped/ descrete frequency distribution
11. Make a program to calculate Quartile Deviation and Coeff. of Quartile Deviation
12. Write a program to calculate mode of a group data

### Create a frequency table of ungrouped data


In [362]:
import numpy as np
from collections import Counter


In [447]:
arr = np.random.randint(1,50,20)
arr1 = Counter(arr)

In [448]:
print('|\tObservation\t|\tFrequency\t|')
print('_'*50)
for i in arr1.items():
    print(f'|\t{i[0]}\t\t|\t{i[1]}\t\t|')
    print('_'*50)

|	Observation	|	Frequency	|
__________________________________________________
|	9		|	2		|
__________________________________________________
|	34		|	1		|
__________________________________________________
|	6		|	1		|
__________________________________________________
|	14		|	1		|
__________________________________________________
|	29		|	1		|
__________________________________________________
|	37		|	1		|
__________________________________________________
|	13		|	2		|
__________________________________________________
|	46		|	1		|
__________________________________________________
|	40		|	1		|
__________________________________________________
|	47		|	2		|
__________________________________________________
|	41		|	1		|
__________________________________________________
|	7		|	1		|
__________________________________________________
|	12		|	1		|
__________________________________________________
|	32		|	1		|
__________________________________________________
|	49		|	1		|
_______________

### 2. Create a frequency table for grouped data exclusive method



In [159]:
arr = np.random.randint(1,200,50)


In [160]:
arr

array([163,  35,  69,  59, 191, 192,  50, 167, 131, 165, 166, 165, 198,
       128,  31, 118,  23,  81, 181, 104,  56, 183,   1, 161, 157, 186,
       116, 190,  79, 134, 145,  25,  86, 137, 109,  53, 109, 164, 116,
       199, 158, 194, 191,  92,  63, 151, 179, 116, 136, 177])

In [161]:
N = len(arr)
k = int(round(1+(3.322*np.log10(N))))
range_ = max(arr)- min(arr)
size = int(round(range_ //k))

In [169]:
def freq_grouped_data(arr):
    N = len(arr)
    k = int(round(1+(3.322*np.log10(N))))
    range_ = max(arr)- min(arr)
    size = int(round(range_ //k))
    intervals = list(range(min(arr),max(arr)+size,size))
    freq = []
    arr1  = list(arr)
    for i in range(len(intervals)-1):
        count = 0
        ll = intervals[i]
        ul = intervals[i+1]
        if ul==max(arr1):
            for j in range(ll,ul+1):
                count+=arr1.count(j)
        else:
            for j in range(ll,ul):
                count+=arr1.count(j)
        freq.append(count)
    print('|\tIntervals\t|\tFrequency\t|')
    print('_'*50)
    for i in range(len(intervals)-1):
        ll = intervals[i]
        ul = intervals[i+1]
        print(f'|\t{ll}-{ul}\t\t|\t{freq[i]}\t\t|')
        print('_'*50)
    


In [170]:
freq_grouped_data(arr)

|	Intervals	|	Frequency	|
__________________________________________________
|	1-29		|	3		|
__________________________________________________
|	29-57		|	5		|
__________________________________________________
|	57-85		|	5		|
__________________________________________________
|	85-113		|	5		|
__________________________________________________
|	113-141		|	9		|
__________________________________________________
|	141-169		|	11		|
__________________________________________________
|	169-197		|	10		|
__________________________________________________
|	197-225		|	2		|
__________________________________________________


### Create a frequency table for grouped data inclusive method

In [43]:
arr = np.random.randint(1,200,50)

In [46]:
arr

array([190, 137, 191, 186, 125,  27, 189,  43, 166, 181,   9, 118,  58,
       101,  39,  60, 132, 113, 193, 143, 100, 175, 156,  31,  32,  11,
        58,  65, 196, 161, 110, 118, 152, 181,  30, 181,  20,  71, 113,
       164,  26, 156,  27, 135,  80, 156, 125, 145,  12, 106])

In [119]:
def freq_grouped1_data(arr):
    N = len(arr)
    k = int(round(1+(3.322*np.log10(N))))
    range_ = max(arr)- min(arr)
    size = int(round(range_ //k))
    intervals = list(range(min(arr),max(arr)+size,size))
    freq = []
    arr1  = list(arr)
    for i in range(len(intervals)-1):
        count = 0
        ll = intervals[i]
        ul = intervals[i+1]
        if ul==max(arr1):
            for j in range(ll,ul):
                count+=arr1.count(j)
        else:
            for j in range(ll,ul):
                count+=arr1.count(j)
        freq.append(count)
    print('|\tIntervals\t|\tFrequency\t|')
    print('_'*50)
    for i in range(len(intervals)-1):
        ll = intervals[i]
        ul = intervals[i+1]-1
        print(f'|\t{ll}-{ul}\t\t|\t{freq[i]}\t\t|')
        print('_'*50)
    


In [121]:
arr

array([124, 131,  55, 159,  56,  25,  91, 161, 143,  46, 185, 137, 143,
       162,  74,  18,  80, 198,  12,   6,  18,   8, 121,  25, 182,  91,
       154,  12,   3, 178,  76,  14,  53, 139, 141, 151, 191, 183,  27,
        95, 195,  85, 102,   5, 107, 164,  79,  13,  34, 175])

In [120]:
freq_grouped1_data(arr)

|	Intervals	|	Frequency	|
__________________________________________________
|	3-29		|	13		|
__________________________________________________
|	30-56		|	5		|
__________________________________________________
|	57-83		|	4		|
__________________________________________________
|	84-110		|	6		|
__________________________________________________
|	111-137		|	4		|
__________________________________________________
|	138-164		|	10		|
__________________________________________________
|	165-191		|	6		|
__________________________________________________
|	192-218		|	2		|
__________________________________________________


### Create a frequency percentage table for grouped data exclusive method 

In [122]:
arr = np.random.randint(1,200,50)

In [123]:
arr

array([118, 102,  83, 124,  76,   1,  63,  66, 128, 117, 126,  93, 171,
        68, 198,  40,  80,  52, 128,   8, 128,  14,  93, 157, 155, 119,
        49,  25, 141, 124,  14,  37, 111, 191,  33, 171, 179, 197, 193,
         2, 118, 125,  91, 131,   1,  98,   2, 119, 167, 127])

In [136]:
def freq_groupedper_data(arr):
    N = len(arr)
    k = int(round(1+(3.322*np.log10(N))))
    range_ = max(arr)- min(arr)
    size = int(round(range_ //k))
    intervals = list(range(min(arr),max(arr)+size,size))
    freq = []
    arr1  = list(arr)
    for i in range(len(intervals)-1):
        count = 0
        ll = intervals[i]
        ul = intervals[i+1]
        if ul==max(arr1):
            for j in range(ll,ul):
                count+=arr1.count(j)
        else:
            for j in range(ll,ul):
                count+=arr1.count(j)
        freq.append(count)
    print('|\tIntervals\t|\tFrequency\t|\tPercentage\t|')
    print('_'*75)
    for i in range(len(intervals)-1):
        ll = intervals[i]
        ul = intervals[i+1]-1
        print(f'|\t{ll}-{ul}\t\t|\t{freq[i]}\t\t|\t{round((freq[i]/N)*100)}\t\t|')
        print('_'*75)
    


In [137]:
freq_groupedper_data(arr)

|	Intervals	|	Frequency	|	Percentage	|
___________________________________________________________________________
|	1-28		|	8		|	16		|
___________________________________________________________________________
|	29-56		|	5		|	10		|
___________________________________________________________________________
|	57-84		|	6		|	12		|
___________________________________________________________________________
|	85-112		|	6		|	12		|
___________________________________________________________________________
|	113-140		|	14		|	28		|
___________________________________________________________________________
|	141-168		|	4		|	8		|
___________________________________________________________________________
|	169-196		|	5		|	10		|
___________________________________________________________________________
|	197-224		|	2		|	4		|
___________________________________________________________________________


### 5. Use exclusive method to create classes and calculate less than and more than cummulative Frequency table


In [147]:
arr = np.random.randint(1,100,50)


In [171]:
N = len(arr)
k = int(round(1+(3.322*np.log10(N))))
range_ = max(arr)- min(arr)
size = int(round(range_ //k))

In [254]:
def freq_cummulative_data(arr):
    N = len(arr)
    k = int(round(1+(3.322*np.log10(N))))
    range_ = max(arr)- min(arr)
    size = int(round(range_ //k))
    intervals = list(range(min(arr),max(arr)+size,size))
    freq = []
    arr1  = list(arr)
    for i in range(len(intervals)-1):
        count = 0
        ll = intervals[i]
        ul = intervals[i+1]
        if ul==max(arr1):
            for j in range(ll,ul+1):
                count+=arr1.count(j)
        else:
            for j in range(ll,ul):
                count+=arr1.count(j)
        freq.append(count)
    c= 0
    l1 = []
    for i in freq:
        c+=i
        l1.append(c)
    c1=0
    l2 = []
    for i in freq[::-1]:
        c1+=i
        l2.append(c1)
    
    print('|\tIntervals\t|\tFrequency\t|\tLess than cumm\t|\tMore than cumm\t|')
    print('_'*100)
    for i in range(len(intervals)-1):

        ll = intervals[i]
        ul = intervals[i+1]
        print(f'|\t{ll}-{ul}\t\t|\t{freq[i]}\t\t|\t{l1[i]}\t\t|\t{l2[-i-1]}\t\t|')
        print('_'*100)
    


In [255]:
freq_cummulative_data(arr)

|	Intervals	|	Frequency	|	Less than cumm	|	More than cumm	|
____________________________________________________________________________________________________
|	1-29		|	3		|	3		|	50		|
____________________________________________________________________________________________________
|	29-57		|	5		|	8		|	47		|
____________________________________________________________________________________________________
|	57-85		|	5		|	13		|	42		|
____________________________________________________________________________________________________
|	85-113		|	5		|	18		|	37		|
____________________________________________________________________________________________________
|	113-141		|	9		|	27		|	32		|
____________________________________________________________________________________________________
|	141-169		|	11		|	38		|	23		|
____________________________________________________________________________________________________
|	169-197		|	10		|	48		|	12		|
_______________________________

### Calculate Cummulative Percentage Freq. Table

In [266]:
arr = np.random.randint(1,100,40)

In [271]:
def freq_cummulative_per_data(arr):
    N = len(arr)
    k = int(round(1+(3.322*np.log10(N))))
    range_ = max(arr)- min(arr)
    size = int(round(range_ //k))
    intervals = list(range(min(arr),max(arr)+size,size))
    freq = []
    arr1  = list(arr)
    for i in range(len(intervals)-1):
        count = 0
        ll = intervals[i]
        ul = intervals[i+1]
        if ul==max(arr1):
            for j in range(ll,ul+1):
                count+=arr1.count(j)
        else:
            for j in range(ll,ul):
                count+=arr1.count(j)
        freq.append(count)
    c= 0
    l1 = []
    for i in freq:
        c+=i
        l1.append(c)
    
    
    print('|\tIntervals\t|\tFrequency\t|\tLess than cumm\t|\tPercentage\t|')
    print('_'*100)
    for i in range(len(intervals)-1):

        ll = intervals[i]
        ul = intervals[i+1]
        print(f'|\t{ll}-{ul}\t\t|\t{freq[i]}\t\t|\t{l1[i]}\t\t|\t{round((l1[i]/N)*100,2)}\t\t|')
        print('_'*100)
    


In [272]:
freq_cummulative_per_data(arr)

|	Intervals	|	Frequency	|	Less than cumm	|	Percentage	|
____________________________________________________________________________________________________
|	2-18		|	8		|	8		|	20.0		|
____________________________________________________________________________________________________
|	18-34		|	3		|	11		|	27.5		|
____________________________________________________________________________________________________
|	34-50		|	9		|	20		|	50.0		|
____________________________________________________________________________________________________
|	50-66		|	3		|	23		|	57.5		|
____________________________________________________________________________________________________
|	66-82		|	7		|	30		|	75.0		|
____________________________________________________________________________________________________
|	82-98		|	8		|	38		|	95.0		|
____________________________________________________________________________________________________
|	98-114		|	2		|	40		|	100.0		|
___________________________

### Calculate mean for grouped data

In [441]:
arr = np.random.randint(1,100,40)

In [442]:
arr

array([60, 54, 46, 76, 73, 81, 30, 88, 57, 69, 23, 73, 18, 74, 68, 31, 23,
       72, 30, 83, 40, 44, 68, 40, 49, 71, 11, 72, 78, 78, 36, 58, 47, 18,
       40, 96, 69, 70, 97, 14])

In [443]:
def mean_grp_data(arr):
    N = len(arr)
    k = int(round(1+(3.322*np.log10(N))))
    range_ = max(arr)-min(arr)
    size = int(round(range_/k))
    intervals = list(range(min(arr),max(arr)+size,size))
    freq=[]
    mid = []
    fd_count = 0
    arr1 =list(arr)
    for i in range(len(intervals)-1):
        ll = intervals[i]
        ul = intervals[i+1]
        X = (ll+ul)//2
        mid.append(X)
        count = 0
        if ul ==max(arr):
            for j in range(ll,ul+1):
                count+=arr1.count(j)
        else:
            for j  in range(ll,ul):
                count+=arr1.count(j)
        freq.append(count)
    A = mid[k//2]
    print('|\tIntervals\t|\tFrequency\t|\tMid (X)\t\t|\td\t\t|\tfd\t\t|')
    print('_'*120)
    for i in range(len(intervals)-1):

        ll = intervals[i]
        ul = intervals[i+1]
        fd_count+=freq[i]*((mid[i]-A)//size)
        
        if A == mid[i]:
            print(f'|\t{ll}-{ul}\t\t|\t{freq[i]}\t\t|\tA[{mid[i]}]\t\t|\t{(mid[i]-A)//size}\t\t|\t{freq[i]*((mid[i]-A)//size)}\t\t|')
            print('_'*120)
        else:
            print(f'|\t{ll}-{ul}\t\t|\t{freq[i]}\t\t|\t{mid[i]}\t\t|\t{(mid[i]-A)//size}\t\t|\t{freq[i]*((mid[i]-A)//size)}\t\t|')
            print('_'*120)
    print(f'|\tTotal\t\t|\t{len(arr)}\t\t|\t\t\t|\t\t\t|\t{fd_count}\t\t|')
    print('_'*120)
            
    
        

In [444]:
mean_grp_data(arr)

|	Intervals	|	Frequency	|	Mid (X)		|	d		|	fd		|
________________________________________________________________________________________________________________________
|	11-25		|	6		|	18		|	-3		|	-18		|
________________________________________________________________________________________________________________________
|	25-39		|	4		|	32		|	-2		|	-8		|
________________________________________________________________________________________________________________________
|	39-53		|	7		|	46		|	-1		|	-7		|
________________________________________________________________________________________________________________________
|	53-67		|	4		|	A[60]		|	0		|	0		|
________________________________________________________________________________________________________________________
|	67-81		|	14		|	74		|	1		|	14		|
________________________________________________________________________________________________________________________
|	81-95		|	3		|	88		|	2		|	6		|
______________________

### Calculate mean for ungrouped/ descrete frequency distribution

In [380]:
arr = np.random.randint(1,25,100)


In [381]:
arr

array([17, 19, 12, 14,  4, 17,  1, 20, 17, 11, 12,  3, 14, 16, 18, 24,  9,
        2, 10, 10, 15, 19, 23,  3, 17,  6,  5, 13,  5, 14,  7, 20, 10,  5,
        4,  8, 11, 15, 10, 20,  3, 17,  9, 14,  2, 21,  4,  2,  1, 10, 17,
        6, 11,  1, 11,  8, 18, 18, 15, 10,  5, 21,  6, 10,  9, 15, 13, 24,
       23, 24, 16, 13, 16, 11, 10, 12, 16, 20, 15,  7,  6, 15, 18, 23, 14,
        2,  3, 23, 12, 12,  2, 21,  1,  1,  1, 17,  5, 21, 11, 15])

In [437]:
def mean_ungrp_data(arr):
    arr1  = Counter(arr)
    l = list(arr1.keys())
    p = len(l)//2
    A = l[p]
    print('|\tX\t|\tf\t|\tfx\t|\td=x-A\t|\tfd\t|')
    print('_'*80)
    fd_count = 0
    fx_count = 0
    for i in arr1.items():
        fd_count+=i[1]*(i[0]-A)
        fx_count+=i[0]*i[1]
        if A == i[0]:
            print(f'|\tA[{i[0]}]\t|\t{i[1]}\t|\t{i[0]*i[1]}\t|\t{i[0]-A}\t|\t{i[1]*(i[0]-A)}\t|')
            print('_'*80)
        else:
            print(f'|\t{i[0]}\t|\t{i[1]}\t|\t{i[0]*i[1]}\t|\t{i[0]-A}\t|\t{i[1]*(i[0]-A)}\t|')
            print('_'*80)
    print(f'|\tTotal\t|\t{len(arr)}\t|\t{fx_count}\t|\t\t|\t{fd_count}\t|')
    print('_'*80)
            
    
        

In [438]:
mean_ungrp_data(arr)

|	X	|	f	|	fx	|	d=x-A	|	fd	|
________________________________________________________________________________
|	17	|	7	|	119	|	-7	|	-49	|
________________________________________________________________________________
|	19	|	2	|	38	|	-5	|	-10	|
________________________________________________________________________________
|	12	|	5	|	60	|	-12	|	-60	|
________________________________________________________________________________
|	14	|	5	|	70	|	-10	|	-50	|
________________________________________________________________________________
|	4	|	3	|	12	|	-20	|	-60	|
________________________________________________________________________________
|	1	|	6	|	6	|	-23	|	-138	|
________________________________________________________________________________
|	20	|	4	|	80	|	-4	|	-16	|
________________________________________________________________________________
|	11	|	6	|	66	|	-13	|	-78	|
________________________________________________________________________________
|	3	|	4	|	12	|	-21	|	-8

### Calculate weighted mean for data

In [449]:
arr = np.random.randint(1,100,20)

In [450]:
arr

array([12, 83,  2, 53, 32, 94, 48, 71, 85, 62, 80,  4, 80, 89, 46, 98, 84,
       19, 66, 27])

In [545]:
def weighted_mean(arr):
    arr1 = Counter(arr)
    wx_count = 0
    print('|\tW\t\t|\tX\t\t|\tWX\t\t|')
    print('_'*70)
    for i in arr1.items():
        wx_count+=i[0]*i[1]
        print(f'|\t{i[0]}\t\t|\t{i[1]}\t\t|\t{i[0]*i[1]}\t\t|')
        print('_'*70)
    print(f'|\tTotal\t\t|\t{len(arr)}\t\t|\t{wx_count}\t\t|')
    return wx_count/len(arr)

In [546]:
weighted_mean(arr)

|	W		|	X		|	WX		|
______________________________________________________________________
|	20		|	3		|	60		|
______________________________________________________________________
|	33		|	2		|	66		|
______________________________________________________________________
|	31		|	4		|	124		|
______________________________________________________________________
|	7		|	4		|	28		|
______________________________________________________________________
|	25		|	3		|	75		|
______________________________________________________________________
|	22		|	4		|	88		|
______________________________________________________________________
|	13		|	3		|	39		|
______________________________________________________________________
|	45		|	4		|	180		|
______________________________________________________________________
|	11		|	2		|	22		|
______________________________________________________________________
|	27		|	2		|	54		|
______________________________________________________________________
|	5		|	2		

23.56

### Median for for ungrouped/ descrete frequency distribution

In [459]:
arr = np.random.randint(1,100,20)

In [460]:
arr

array([ 7, 42, 53, 72, 76, 53, 88,  5, 38, 90, 93, 95, 82, 57, 13, 26,  8,
       92, 46, 11])

In [549]:
def median_ungrp_data(arr):
    N = len(arr)
    k = int(round(1+(3.322*np.log10(N))))
    range_ = max(arr)- min(arr)
    size = int(round(range_ //k))
    intervals = list(range(min(arr),max(arr)+size,size))
    freq = []
    cumm = []
    lcf = 0
    arr1  = list(arr)
    for i in range(len(intervals)-1):
        count = 0
        ll = intervals[i]
        ul = intervals[i+1]
        if ul==max(arr1):
            for j in range(ll,ul+1):
                count+=arr1.count(j)
        else:
            for j in range(ll,ul):
                count+=arr1.count(j)
        lcf+=count
        cumm.append(lcf)
        freq.append(count)
    
    print('|\tIntervals\t|\tFrequency\t|\tcumm\t\t|')
    print('_'*75)
    for i in range(len(intervals)-1):
        ll = intervals[i]
        ul = intervals[i+1]

        print(f'|\t{ll}-{ul}\t\t|\t{freq[i]}\t\t|\t{cumm[i]}\t\t|')
        print('_'*75)
    for i in range(len(intervals)-1):
        ll = intervals[i]
        ul = intervals[i+1]
        if cumm[i]>=N/2:
            m = ll+((N/2-cumm[i-1])/freq[i])*size
            break
        
        
    return m
            
    

        

   

In [550]:
median_ungrp_data(arr)

|	Intervals	|	Frequency	|	cumm		|
___________________________________________________________________________
|	1-7		|	11		|	11		|
___________________________________________________________________________
|	7-13		|	16		|	27		|
___________________________________________________________________________
|	13-19		|	13		|	40		|
___________________________________________________________________________
|	19-25		|	14		|	54		|
___________________________________________________________________________
|	25-31		|	9		|	63		|
___________________________________________________________________________
|	31-37		|	17		|	80		|
___________________________________________________________________________
|	37-43		|	7		|	87		|
___________________________________________________________________________
|	43-49		|	13		|	100		|
___________________________________________________________________________


23.285714285714285

### Write a program to calculate mode of a group data

In [481]:
arr = np.random.randint(1,50,100)

In [482]:
arr

array([20, 33, 31,  7, 25, 22, 13, 45, 11, 27,  5, 36, 45, 43, 49,  7, 17,
       26, 13, 16, 21, 28,  8, 34, 31, 17, 29,  1, 35, 25, 23, 10, 34, 32,
        1, 20, 24, 18, 12, 42, 39,  5, 16,  2, 44, 14,  3,  3, 49, 16, 31,
       45, 21, 35, 13, 20, 22, 26, 27,  4,  9, 44, 10, 39, 43, 33,  7, 36,
       12, 21, 37, 39,  2,  4, 46, 11, 31, 37, 12,  8, 25, 49, 43, 38, 21,
       24, 17, 14, 32, 22, 45, 34,  9,  7, 22,  6, 36,  9, 35, 16])

In [505]:
def mode_grp_data(arr):
    N = len(arr)
    k = int(round(1+(3.322*np.log10(N))))
    range_ = max(arr)-min(arr)
    size = int(round(range_//k))
    intervals = list(range(min(arr),max(arr)+size,size))
    freq = []
    arr1 = list(arr)
    for i in range(len(intervals)-1):
        count = 0
        ll = intervals[i]
        ul = intervals[i+1]
        if ul == max(arr):
            for j in range(ll,ul+1):
                count+=arr1.count(j)
        else:
            for j in range(ll,ul):
                count+=arr1.count(j)
        freq.append(count)
    print('|\tC-I\t\t|\tf\t\t|')
    print('_'*50)
    for i in range(len(intervals)-1):
        ll = intervals[i]
        ul = intervals[i+1]
        if max(freq)==freq[i]:
            print(f'|\t{ll}-{ul}\t\t|\tf1[{freq[i]}]\t\t|')
            print('_'*50)
            m=ll+((freq[i]-freq[i-1])/(2*freq[i]-freq[i-1]-freq[i+1]))*size
        else:
            print(f'|\t{ll}-{ul}\t\t|\t{freq[i]}\t\t|')
            print('_'*50)
    return m
            
    
            
    
        

In [506]:
mode_grp_data(arr)

|	C-I		|	f		|
__________________________________________________
|	1-7		|	11		|
__________________________________________________
|	7-13		|	16		|
__________________________________________________
|	13-19		|	13		|
__________________________________________________
|	19-25		|	14		|
__________________________________________________
|	25-31		|	9		|
__________________________________________________
|	31-37		|	f1[17]		|
__________________________________________________
|	37-43		|	7		|
__________________________________________________
|	43-49		|	13		|
__________________________________________________


33.666666666666664